server:
  port: 8012
spring:
  profiles:
    active:
    - native
  application:
    name: PhotoAppConfigServer
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          default-label: feature
          password: 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
          uri: https://github.com/grootenthu/CommonConfig
          username: grootenthu
        native:
          search-locations:
          - file://${user.home}/config_server
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include:
        - busrefresh
